export const APPOINTMENT_TIME_RANGES = [
  ['10:00', '11:30'],
  ['14:00', '19:30'],
];

export const APPOINTMENT_TIME_MINUTE_STEP = 15;
export const DEFAULT_ESTIMATED_DURATION_MINUTES = 15;
export const MAX_ESTIMATED_DURATION_MINUTES = 240;
